const express = require("express");
const app = express();
const schedule = require("node-schedule");

const bodyParser = require("body-parser");

const low = require("lowdb");
const FileSync = require("lowdb/adapters/FileSync");

const adapter = new FileSync("db.json");
const db = low(adapter);

const nodemailer = require("nodemailer");
const Email = require("email-templates");

const axios = require("axios");
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

const transporter = nodemailer.createTransport({
  host: "smtp.mailtrap.io",
  port: 2525,
  auth: {
    user: "da9edd1144c4cc", //generated by Mailtrap
    pass: "d4cf1d2e4a77b7", //generated by Mailtrap
  },
});

app.get("/", function (req, res) {
  res.status(500).json({ error: "message" });
});

app.get("/dbsetup", function (req, res) {
  db.defaults({ posts: [], user: {} }).write();
  res.status(200).json({ msg: "dbsetup done" });
});

app.get("/subscribe", function (req, res) {
  db.get("posts").push(req.body).write();
  res.status(200).json({ msg: "thanks for subscibing" });
});


schedule.scheduleJob("1 * * * * *", function () {
    const posts = db.get("posts").value();
    posts.forEach((element) => {
      axios
        .get(
          "http://api.weatherstack.com/current?access_key=71dcd2b11b08fc32fd7afbf66774fd4f&query=28.0229,73.3119"
        )
        .then(function (res) {
          // console.log(res)
          const html = `<img src=${res.data.current.weather_icons[0]} /><h1>${res.data.location.name}</h1><h2>Temp:${res.data.current.temperature}</h2><h2>Humidity:${res.data.current.humidity}</h2>`;
          const mailOptions = {
            from: "rmodi2407@gmail.com",
            to: element.email,
            subject: "Weather news ",
            html: html,
          };
  
          transporter.sendMail(mailOptions, function (error, info) {
            if (error) {
              console.log(error);
            } else {
              console.log("Email sent: " + info.response);
            }
          });
        });
    });
});
app.listen(3000, () => console.log("server is running"));
